# -*- coding: utf-8 -*-
"""Resume parser project (Susmiha,Shamyuktha,Narin,Melvin).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckad4t-N8X_nVv1m5IfBfoPZ4XHaMCq9
"""

!pip install -q faiss-cpu sentence-transformers PyPDF2

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from google.colab import files
import PyPDF2
import re

uploaded = files.upload()

def extract_text(uploaded_files):
    for file in uploaded_files:
        if file.endswith(".pdf"):
            text = ""
            with open(file, "rb") as f:
                reader = PyPDF2.PdfReader(f)
                for page in reader.pages:
                    text += page.extract_text() or ""
            return text.lower()

        elif file.endswith(".txt"):
            with open(file, "r", encoding="utf-8") as f:
                return f.read().lower()
    return ""

resume_text = extract_text(uploaded)
print(resume_text[:1200])

JOB_ROLES = {
    "UX Designer": {
        "skills": ["ui", "ux", "figma", "wireframe", "prototype", "design"],
        "languages": []
    },
    "Product Owner": {
        "skills": ["product", "roadmap", "stakeholder", "agile", "scrum"],
        "languages": []
    },
    "HR": {
        "skills": ["recruitment", "hr", "hiring", "payroll", "onboarding"],
        "languages": []
    },
    "QA": {
        "skills": ["testing", "qa", "automation", "selenium", "manual"],
        "languages": ["java", "python"]
    },
    "Developer": {
        "skills": ["programming", "backend", "frontend", "api", "software"],
        "languages": ["python", "java", "c++", "javascript"]
    }
}

def calculate_score(resume, role_data):
    score = 0

    resume = resume.lower()

    # 1️⃣ Skill matching
    for skill in role_data.get("skills", []):
        if skill in resume:
            score += 5

    # 2️⃣ Language matching
    for lang in role_data.get("languages", []):
        if lang in resume:
            score += 3

    # 3️⃣ Experience-based scoring (simple & safe)
    if "year" in resume or "years" in resume or "experience" in resume:
        score += 5

    # 4️⃣ Education-based scoring
    education_keywords = ["bachelor", "b.tech", "btech", "degree", "master", "m.tech", "mba"]
    for edu in education_keywords:
        if edu in resume:
            score += 3
            break   # count education only once

    return score

scores = {}

for role, data in JOB_ROLES.items():
    scores[role] = calculate_score(resume_text, data)

ranked_roles = sorted(scores.items(), key=lambda x: x[1], reverse=True)

print("🔹 Job Match Ranking:\n")
for role, score in ranked_roles:
    print(f"{role} → Score: {score}")

best_role = ranked_roles[0][0]

print("\n✅ Best Suitable Job Role:", best_role)

!pip install -q transformers torch

from transformers import pipeline

explainer = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=80
)

def explain_role_hf(resume_text, best_role):
    prompt = f"""
    Resume skills and experience:
    {resume_text[:800]}

    Question:
    Why is this resume suitable for the role of {best_role}?
    """

    result = explainer(prompt)
    return result[0]["generated_text"]

explanation = explain_role_hf(resume_text, best_role)
print("📌 Explanation:\n", explanation)

def skill_coverage(resume, role_data):
    total = len(role_data["skills"])
    matched = sum(1 for s in role_data["skills"] if s in resume)
    return round((matched / total) * 100, 2) if total > 0 else 0

coverage = skill_coverage(resume_text, JOB_ROLES[best_role])
print("Skill Match %:", coverage)

def resume_quality_score(resume):
    score = 0
    if len(resume.split()) > 150:
        score += 5
    if "skills" in resume:
        score += 5
    if "experience" in resume:
        score += 5
    if "education" in resume:
        score += 5
    return score

print("Resume Quality Score:", resume_quality_score(resume_text))